apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ch07-app
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: ch07-app
    spec:
      containers:
      - name: ch07-app
        image: webapp:1
        # for local development against minikube registry
        #imagePullPolicy: Never        
        ports:
        - containerPort: 80
        ## Watson Visual Recognitionのサービス紐付けサンプルです。
        ## Visual RecognitionサービスをデプロイしてService Binding Secret Nameを置き換えてください。
        env:
        - name: WATSON_VR
          valueFrom:
           secretKeyRef:
           # name: {ServiceBinding Secret name}
             name: binding-watson-vr-gb
             key: binding
---
apiVersion: v1
kind: Service
metadata:
  name: ch07-service
  labels:
    app: ch07-service
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
    - port: 80
  # label keys and values that must match in order to receive traffic for this service
  selector:
    app: ch07-app
